# Generated by Django 2.2.12 on 2020-05-18 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hd',
            fields=[
                ('loc', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('no_of_p', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('hid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('hname', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('hphone', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('pid', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('dob', models.DateField(verbose_name='date of Birth')),
                ('phno', models.IntegerField(default=0)),
                ('doorno', models.IntegerField(default=0)),
                ('street', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('previous_health_issue', models.CharField(max_length=200)),
                ('hid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Hospital')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalCamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.IntegerField(default=0)),
                ('campname', models.CharField(max_length=200)),
                ('mcloc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.hd')),
            ],
        ),
        migrations.CreateModel(
            name='dependent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=200)),
                ('drelation', models.CharField(max_length=200)),
                ('dph', models.IntegerField(default=0)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.People')),
            ],
        ),
    ]
