# Generated by Django 2.2.12 on 2020-05-19 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCamp1',
            fields=[
                ('area', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('hid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Hospital')),
            ],
        ),
    ]
