# Generated by Django 2.2.12 on 2020-05-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_medicalcamp1'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcamp1',
            name='staffcount',
            field=models.IntegerField(default=0),
        ),
    ]
