# Generated by Django 2.2.12 on 2020-05-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_disease_healthissues_medicationtable_medicinetable_statustype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
