# Generated by Django 2.2.12 on 2020-05-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_gender1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gender1',
            name='id',
        ),
        migrations.AlterField(
            model_name='gender1',
            name='gender',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
