# Generated by Django 2.2.12 on 2020-05-23 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_auto_20200523_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Gender1'),
        ),
    ]
